version: '3.8'

services:
  # MySQL instance for Luxury-Wear-Service
  luxury-wear-db:
    container_name: mysqldb
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - luxury-wear-network
    ports:
      - "3307:3306"

  # LuxuryWearService application
  luxury-wear-service:
    build:
      context: .  # Context is the current directory (luxury-wear-service)
    ports:
      - "8080:8080"
    environment:
      SPRING_JDBC_URL: jdbc:mysql://luxury-wear-db:3306/luxury_wear_db_v2?createDatabaseIfNotExist=true
      SPRING_JDBC_USERNAME: root
      SPRING_JDBC_PASSWORD: rootpassword
      ACTIVE_PROFILE: mysql
    depends_on:
      luxury-wear-db:
        condition: service_healthy
    networks:
      - luxury-wear-network

networks:
  luxury-wear-network:
    driver: bridge

volumes:
  mysql-data:
